spring:
  datasource:
    url: jdbc:mysql://114.115.248.134:3306/notice_app?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      write-dates-as-timestamps: true
